// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types/mkdefs.go

package main

type socketsDef struct {
	Pid		int32
	ProcessName	[32]int8
	Socket_type	uint32
	Connection_type	uint32
	DestIPAddr	[16]int8
	SourcePort	uint16
	DestPort	uint16
	Local		int32
	Listening	int32
}
